name: Build

on:
  push:
    - main
  pull_request:

jobs:
  build:
    name: Zig build check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@0c366fd6a839edf440554fa01a7085ccba70ac98

      - name: Setup Zig
        uses: https://codeberg.org/mlugg/setup-zig@d1434d08867e3ee9daa34448df10607b98908d29
        with:
          version: 0.15.2

      - name: Run build check
        run: zig build check
