name: Test

on:
  push:
    branches: [main]
  pull_request:

jobs:
  tests:
    name: tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@0c366fd6a839edf440554fa01a7085ccba70ac98

      - name: Setup Zig
        uses: https://codeberg.org/mlugg/setup-zig@d1434d08867e3ee9daa34448df10607b98908d29
        with:
          version: 0.15.2

      - name: Install project dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            glslang-tools \
            libvulkan-dev \
            libwayland-bin \
            libwayland-dev \
            libxkbcommon-dev \
            spirv-tools \
            wayland-protocols

      - name: Run tests
        run: zig build test
